// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"greet/internal/svc"

	"github.com/tal-tech/go-zero/rest"
)

func RegisterHandlers(engine *rest.Server, serverCtx *svc.ServiceContext) {
	engine.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/api/v1/passwd",
				Handler: QueryPasswordHandler(serverCtx),
			},
			{
				Method: http.MethodGet,
				Path: "/api/v1/alluser",
				Handler: GetAllUserHandler(serverCtx),
			},
		},
	)
}
